### ISSUE TITLE
HW 7 problem 2 Matlab script

### ISSUE THREAD

**Issue by EmreBayat** [coghex/ecen5018#1]
Could you please share problem 2 Matlab script for HW7

**Comment by coghex** [comment]
Sorry, I don’t have any files from back then, gl

**Comment by EmreBayat** [comment]
thanks. do you have any book or lecture notes to solve Problem 1 in the HW7. Thanks. Because I couldn't understand how we can write payoff matrix.

**Comment by coghex** [comment]
Sorry, I threw away everything from college, I remember those being very complicated though, I had to copy off of a friend.
